version: '3.8'

services:
  examportal:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - monitoring
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

    
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - monitoring
    env_file:
      - .env


networks:
  monitoring: