global:
  scrape_interval: 1d  # How frequently to scrape targets

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the ExamPortal application running on Render
  - job_name: 'examportal-app'
    basic_auth:
      username: '${PROMETHEUS_USERNAME}'  # Use environment variable for username
      password: '${PROMETHEUS_PASSWORD}'  # Use environment variable for password
    static_configs:
      - targets: ['localhost:3000']

