global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['examportal:3000']
  - job_name: 'prod-app'
    scheme: https
    static_configs:
      - targets: ['examportal-4.onrender.com']
