global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the ExamPortal application running on Render
  - job_name: 'examportal-app'
    static_configs:
      - targets: ['examportal-4.onrender.com']

  # (Optional) If deploying Prometheus as a separate Render service and need service discovery
  # Uncomment and adjust this section if you need dynamic discovery of other Render services
  # - job_name: 'render-service-discovery'
  #   dns_sd_configs:
  #     - names: ['examportal-4-discovery']
  #       type: A
  #       port: 3000
  #       refresh_interval: 5s # Refresh every 5 seconds
